export const ADD_DEFECT = 'ADD_DEFECT';
export const FETCH_DEFECT='FETCH_DEFECT';
export const UPDATE_DEFECT='UPDATE_DEFECT';

//add form
export const VIEW_DEFECT_ADD_DRAWER_FORM ='VIEW_DEFECT_ADD_DRAWER_FORM';
export const CLOSE_DEFECT_ADD_DRAWER_FORM ='CLOSE_DEFECT_ADD_DRAWER_FORM';

//update form actions
export const VIEW_DEFECT_UPDATE_DRAWER_FORM ='VIEW_DEFECT_UPDATE_DRAWER_FORM';
export const CLOSE_DEFECT_UPDATE_DRAWER_FORM ='CLOSE_DEFECT_UPDATE_DRAWER_FORM';
